Imports WIN.TECHNICAL.PDF_PRINTER
Imports System.Runtime.InteropServices

Public Class PdfCompilerASSEGGNO_INCLUSIONE
    Implements IDocumentCreatorAdapter

    Private pdf As PdfCompiler
    Private tp As TipoPrestazione
    Private fileInput As String
    Private fileOutput As String
    <DllImport("kernel32.dll", SetLastError:=True)> _
    Public Shared Function LoadLibrary(ByVal lpFileName As String) As IntPtr
    End Function

    Public Sub CreateDocument(ByVal Prestazione As Prestazione) Implements IDocumentCreatorAdapter.CreateDocument
        Dim m_TipoPrestazione As TipoPrestazione = CType(Prestazione.TipoPrestazione, TipoPrestazione)

        With m_TipoPrestazione
            If .FileModelloExist Then

                Prestazione.SetFileOutput(.GetFileOutputName(Prestazione.Utente))

                tp = Prestazione.TipoPrestazione()
                fileInput = tp.NomeFileModello
                fileOutput = Prestazione.FileOutPut
                pdf = New PdfCompiler(fileInput, fileOutput)
                pdf.Setup()
                'pdf.SetCampo("nome", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("cognome coniuge", "")
                'pdf.SetCampo("datanascita", Prestazione.Utente.DataNascita)
                'pdf.SetCampo("M/F", RetrieveSesso(Prestazione))
                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)

                'pdf.SetCampo("comune nascita", Prestazione.Utente.ComuneNascita.Descrizione)

                'pdf.SetCampo("provnascita", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("cittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("comuneresidenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("indirizzoresidenza", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("provresidenza", Prestazione.Utente.Residenza.Provincia.Sigla)
                'pdf.SetCampo("capresidenza", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("telefono", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("email", Prestazione.Utente.Comunicazione.Mail)
                'pdf.SetCampo("sede inps", "")
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)
                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)



                '*********************************************************
                'pdf.SetCampo("periodo_1", "periodo_1")
                'pdf.SetCampo("periodo_2", "periodo_2")
                pdf.SetCampo("sede/inps", Prestazione.Utente.Segreteria.Comune)
                pdf.SetCampo("nome", Prestazione.Utente.Nome)
                pdf.SetCampo("cognome", Prestazione.Utente.Cognome)
                pdf.SetCampo("cod_fisc", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("cognome coniuge", "")
                pdf.SetCampo("data_nasc", Prestazione.Utente.DataNascita)
                pdf.SetCampo("luogo_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                pdf.SetCampo("cittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                pdf.SetCampo("luogo_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                pdf.SetCampo("stato_res", Prestazione.Utente.Nazionalita.Descrizione)
                pdf.SetCampo("indirizzo", Prestazione.Utente.Residenza.Via)
                pdf.SetCampo("cap", Prestazione.Utente.Residenza.Comune.CAP)
                pdf.SetCampo("tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                pdf.SetCampo("cell", Prestazione.Utente.Comunicazione.Cellulare1)
                pdf.SetCampo("e_mail", Prestazione.Utente.Comunicazione.Mail)


                pdf.SetCampo("nome_con", Prestazione.Utente.SituazioneFamiliare.Coniuge.Nome)
                pdf.SetCampo("cognome_con", Prestazione.Utente.SituazioneFamiliare.Coniuge.Cognome)
                pdf.SetCampo("cod_fisc_con", Prestazione.Utente.SituazioneFamiliare.Coniuge.CodiceFiscale)
                'pdf.SetCampo("nome", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("cognome coniuge", "")
                'pdf.SetCampo("datanascita", Prestazione.Utente.DataNascita)
                'pdf.SetCampo("M/F", RetrieveSesso(Prestazione))
                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("comune nascita", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("provnascita", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("cittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("comuneresidenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("indirizzoresidenza", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("provresidenza", Prestazione.Utente.Residenza.Provincia.Sigla)
                'pdf.SetCampo("capresidenza", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("telefono", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("email", Prestazione.Utente.Comunicazione.Mail)
                'pdf.SetCampo("sede inps", "")
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)

                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)

                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)

                'pdf.SetCampo("stato_nasc", "stato_nasc")
                'pdf.SetCampo("data/mod", "data/mod")
                'pdf.SetCampo("stato_nasc_3", "stato_nasc_3")
                'pdf.SetCampo("luogo_resid_13", "luogo_resid_13")
                'pdf.SetCampo("stato_resid_11", "stato_resid_11")
                'pdf.SetCampo("info_18a", "info_18a")
                'pdf.SetCampo("cod_fisc_2", "cod_fisc_2")
                'pdf.SetCampo("cod_fisc_16", "cod_fisc_16")
                'pdf.SetCampo("decorr_3", "decorr_3")
                'pdf.SetCampo("cognome", "cognome")
                'pdf.SetCampo("nome_10", "nome_10")
                'pdf.SetCampo("descrizione", "descrizione")
                'pdf.SetCampo("luogo_nasc_1", "luogo_nasc_1")
                'pdf.SetCampo("data_nasc_13", "data_nasc_13")
                'pdf.SetCampo("luogo_nasc_11", "luogo_nasc_11")
                'pdf.SetCampo("luogo_nasc_10", "luogo_nasc_10")
                'pdf.SetCampo("luogo_nasc_13", "luogo_nasc_13")
                'pdf.SetCampo("luogo_nasc_12", "luogo_nasc_12")
                'pdf.SetCampo("luogo_nasc_15", "luogo_nasc_15")
                'pdf.SetCampo("luogo_nasc_14", "luogo_nasc_14")
                'pdf.SetCampo("luogo_nasc_17", "luogo_nasc_17")
                'pdf.SetCampo("luogo_nasc_16", "luogo_nasc_16")
                'pdf.SetCampo("prov_nasc_18", "prov_nasc_18")
                'pdf.SetCampo("luogo_nasc_4", "luogo_nasc_4")
                'pdf.SetCampo("data_nasc_6", "data_nasc_6")
                'pdf.SetCampo("nome_7", "nome_7")
                'pdf.SetCampo("prov_nasc_8", "prov_nasc_8")
                'pdf.SetCampo("tel", "tel")
                'pdf.SetCampo("stato_nasc_13", "stato_nasc_13")
                'pdf.SetCampo("stato_nasc_12", "stato_nasc_12")
                'pdf.SetCampo("indirizzo_13", "indirizzo_13")
                'pdf.SetCampo("prov_az_1", "prov_az_1")
                'pdf.SetCampo("prov_nasc_5", "prov_nasc_5")
                'pdf.SetCampo("prov_nasc_6", "prov_nasc_6")
                'pdf.SetCampo("nome_15", "nome_15")
                'pdf.SetCampo("stato_res", "stato_res")
                'pdf.SetCampo("info_18b", "info_18b")
                'pdf.SetCampo("cognome_13", "cognome_13")
                'pdf.SetCampo("nome_2", "nome_2")
                'pdf.SetCampo("motivo_1", "motivo_1")
                'pdf.SetCampo("cod_fisc_con", "cod_fisc_con")
                'pdf.SetCampo("decorr_4", "decorr_4")
                'pdf.SetCampo("prov_nasc_14", "prov_nasc_14")
                'pdf.SetCampo("luogo_nasc_8", "luogo_nasc_8")
                'pdf.SetCampo("cod_fisc_6", "cod_fisc_6")
                'pdf.SetCampo("data_nasc_12", "data_nasc_12")
                'pdf.SetCampo("decorr_9", "decorr_9")
                'pdf.SetCampo("prov_nasc_7", "prov_nasc_7")
                'pdf.SetCampo("nome_17", "nome_17")
                'pdf.SetCampo("stato_resid_13", "stato_resid_13")
                'pdf.SetCampo("cognome_18", "cognome_18")
                'pdf.SetCampo("cap_14", "cap_14")
                'pdf.SetCampo("cod_fisc_10", "cod_fisc_10")
                'pdf.SetCampo("cittadinanza", "cittadinanza")
                'pdf.SetCampo("cap", "cap")
                'pdf.SetCampo("cognome_con", "cognome_con")
                'pdf.SetCampo("info_16b", "info_16b")
                'pdf.SetCampo("cod_fisc_3", "cod_fisc_3")
                'pdf.SetCampo("stato_nasc_1", "stato_nasc_1")
                'pdf.SetCampo("cap_13", "cap_13")
                'pdf.SetCampo("info_17e", "info_17e")
                'pdf.SetCampo("decorr_17", "decorr_17")
                'pdf.SetCampo("info_18c", "info_18c")
                'pdf.SetCampo("luogo_resid_14", "luogo_resid_14")
                'pdf.SetCampo("decorr_14", "decorr_14")
                'pdf.SetCampo("prov_nasc_2", "prov_nasc_2")
                'pdf.SetCampo("decorr_12", "decorr_12")
                'pdf.SetCampo("decorr_11", "decorr_11")
                'pdf.SetCampo("decorr_10", "decorr_10")
                'pdf.SetCampo("cod_fisc_8", "cod_fisc_8")
                'pdf.SetCampo("decorr_5", "decorr_5")
                'pdf.SetCampo("prov_nasc_15", "prov_nasc_15")
                'pdf.SetCampo("data_nasc_9", "data_nasc_9")
                'pdf.SetCampo("nome_6", "nome_6")
                'pdf.SetCampo("data_nasc_11", "data_nasc_11")
                'pdf.SetCampo("indirizzo", "indirizzo")
                'pdf.SetCampo("decorr_8", "decorr_8")
                'pdf.SetCampo("e_mail", "e_mail")
                'pdf.SetCampo("cognome_15", "cognome_15")
                'pdf.SetCampo("data_nasc_16", "data_nasc_16")
                'pdf.SetCampo("info_16c", "info_16c")
                'pdf.SetCampo("cognome_14", "cognome_14")
                'pdf.SetCampo("nome_1", "nome_1")
                'pdf.SetCampo("cod_fisc_17", "cod_fisc_17")
                'pdf.SetCampo("indirizzo_11", "indirizzo_11")
                'pdf.SetCampo("stato_nasc_6", "stato_nasc_6")
                'pdf.SetCampo("info_17a", "info_17a")
                'pdf.SetCampo("cognome_5", "cognome_5")
                'pdf.SetCampo("prov_nasc_9", "prov_nasc_9")
                'pdf.SetCampo("cognome_7", "cognome_7")
                'pdf.SetCampo("nome_11", "nome_11")
                'pdf.SetCampo("cognome_1", "cognome_1")
                'pdf.SetCampo("cognome_3", "cognome_3")
                'pdf.SetCampo("cod_fisc_7", "cod_fisc_7")
                'pdf.SetCampo("data_nasc_4", "data_nasc_4")
                'pdf.SetCampo("cell", "cell")
                'pdf.SetCampo("decorr_6", "decorr_6")
                'pdf.SetCampo("prov_nasc_12", "prov_nasc_12")
                'pdf.SetCampo("data_nasc_10", "data_nasc_10")
                'pdf.SetCampo("info_15a", "info_15a")
                'pdf.SetCampo("luogo_res", "luogo_res")
                'pdf.SetCampo("nome_13", "nome_13")
                'pdf.SetCampo("nome_16", "nome_16")
                'pdf.SetCampo("nome", "nome")
                'pdf.SetCampo("cap_12", "cap_12")
                'pdf.SetCampo("info_16d", "info_16d")
                'pdf.SetCampo("data_nasc_3", "data_nasc_3")
                'pdf.SetCampo("prov_nasc_4", "prov_nasc_4")
                'pdf.SetCampo("stato_nasc_7", "stato_nasc_7")
                'pdf.SetCampo("info_17b", "info_17b")
                'pdf.SetCampo("cod_fisc_9", "cod_fisc_9")
                'pdf.SetCampo("azienda_1", "azienda_1")
                'pdf.SetCampo("sede/inps", "sede/inps")
                'pdf.SetCampo("cognome_10", "cognome_10")
                'pdf.SetCampo("nome_5", "nome_5")
                'pdf.SetCampo("cod_fisc_15", "cod_fisc_15")
                'pdf.SetCampo("prov_nasc_16", "prov_nasc_16")
                'pdf.SetCampo("stato_nasc_8", "stato_nasc_8")
                'pdf.SetCampo("nome_18", "nome_18")
                'pdf.SetCampo("stato_nasc_15", "stato_nasc_15")
                'pdf.SetCampo("stato_nasc_17", "stato_nasc_17")
                'pdf.SetCampo("nome_con_2", "nome_con_2")
                'pdf.SetCampo("prov_nasc_13", "prov_nasc_13")
                'pdf.SetCampo("cod_fisc_11", "cod_fisc_11")
                'pdf.SetCampo("luogo_nasc", "luogo_nasc")
                'pdf.SetCampo("data_nasc_17", "data_nasc_17")
                'pdf.SetCampo("info_15b", "info_15b")
                'pdf.SetCampo("attiv_azienda_1", "attiv_azienda_1")
                'pdf.SetCampo("cod_fisc", "cod_fisc")
                'pdf.SetCampo("indirizzo_12", "indirizzo_12")
                'pdf.SetCampo("dataversione", "dataversione")
                'pdf.SetCampo("cognome_16", "cognome_16")
                'pdf.SetCampo("cod_fisc_13", "cod_fisc_13")
                'pdf.SetCampo("PIN", "PIN")
                'pdf.SetCampo("stato_nasc_4", "stato_nasc_4")
                'pdf.SetCampo("info_17c", "info_17c")
                'pdf.SetCampo("protocollo", "protocollo")
                'pdf.SetCampo("data_nasc_8", "data_nasc_8")
                'pdf.SetCampo("luogo_resid_11", "luogo_resid_11")
                'pdf.SetCampo("prov_nasc_17", "prov_nasc_17 ")
                'pdf.SetCampo("stato_nasc_9", "stato_nasc_9")
                'pdf.SetCampo("nomefile", "nomefile")
                'pdf.SetCampo("data_nasc_5", "data_nasc_5")
                'pdf.SetCampo("prov_nasc_10", "prov_nasc_10")
                'pdf.SetCampo("nome_9", "nome_9")
                'pdf.SetCampo("stato_nasc_11", "stato_nasc_11")
                'pdf.SetCampo("stato_nasc_10", "stato_nasc_10")
                'pdf.SetCampo("decorr_16", "decorr_16")
                'pdf.SetCampo("decorr_15", "decorr_15")
                'pdf.SetCampo("info_15c", "info_15c")
                'pdf.SetCampo("decorr_13", "decorr_13")
                'pdf.SetCampo("luogo_nasc_7", "luogo_nasc_7")
                'pdf.SetCampo("stato_nasc_16", "stato_nasc_16")
                'pdf.SetCampo("stato_nasc_18", "stato_nasc_18")
                'pdf.SetCampo("comune_az_1", "comune_az_1")
                'pdf.SetCampo("info_16a", "info_16a")
                'pdf.SetCampo("decorr_18", "decorr_18")
                'pdf.SetCampo("cod_fisc_18", "cod_fisc_18")
                'pdf.SetCampo("nome_12", "nome_12")
                'pdf.SetCampo("cognome_11", "cognome_11")
                'pdf.SetCampo("nome_4", "nome_4")
                'pdf.SetCampo("luogo_resid_12", "luogo_resid_12")
                'pdf.SetCampo("data_nasc_7", "data_nasc_7")
                'pdf.SetCampo("indirizzo_14", "indirizzo_14")
                'pdf.SetCampo("stato_nasc_5", "stato_nasc_5")
                'pdf.SetCampo("info_17d", "info_17d")
                'pdf.SetCampo("cod_fisc_4", "cod_fisc_4")
                'pdf.SetCampo("info_16e", "info_16e")
                'pdf.SetCampo("luogo_nasc_9", "luogo_nasc_9")
                'pdf.SetCampo("decorr_1", "decorr_1")
                'pdf.SetCampo("nome_14", "nome_14")
                'pdf.SetCampo("prov_nasc", "prov_nasc")
                'pdf.SetCampo("prov_nasc_11", "prov_nasc_11")
                'pdf.SetCampo("luogo_nasc_3", "luogo_nasc_3")
                'pdf.SetCampo("data_nasc_1", "data_nasc_1")
                'pdf.SetCampo("cod_fisc_1", "cod_fisc_1")
                'pdf.SetCampo("decorr_7", "decorr_7")
                'pdf.SetCampo("data_nasc_15", "data_nasc_15")
                'pdf.SetCampo("info_15d", "info_15d")
                'pdf.SetCampo("luogo_nasc_6", "luogo_nasc_6")
                'pdf.SetCampo("data_nasc_2", "data_nasc_2")
                'pdf.SetCampo("stato_resid_12", "stato_resid_12")
                'pdf.SetCampo("stato_resid_14", "stato_resid_14")
                'pdf.SetCampo("data_nasc_18", "data_nasc_18")
                'pdf.SetCampo("cap_11", "cap_11")
                'pdf.SetCampo("info_18d", "info_18d")
                'pdf.SetCampo("indirizzo_azienda_1", "indirizzo_azienda_1")
                'pdf.SetCampo("cognome_con_2", "cognome_con_2")
                'pdf.SetCampo("cognome_9", "cognome_9")
                'pdf.SetCampo("cognome_8", "cognome_8")
                'pdf.SetCampo("prov_nasc_1", "prov_nasc_1")
                'pdf.SetCampo("cognome_4", "cognome_4")
                'pdf.SetCampo("stato_nasc_2", "stato_nasc_2")
                'pdf.SetCampo("cognome_17", "cognome_17")
                'pdf.SetCampo("cognome_6", "cognome_6")
                'pdf.SetCampo("nome_8", "nome_8")
                'pdf.SetCampo("cognome_2", "cognome_2")
                'pdf.SetCampo("cod_fisc_12", "cod_fisc_12")
                'pdf.SetCampo("luogo_nasc_18", "luogo_nasc_18")
                'pdf.SetCampo("cod_fisc_con_2", "cod_fisc_con_2")
                'pdf.SetCampo("decorr_2", "decorr_2")
                'pdf.SetCampo("info_18e", "info_18e")
                'pdf.SetCampo("data_nasc", "data_nasc")
                'pdf.SetCampo("prov_res", "prov_res")
                'pdf.SetCampo("luogo_nasc_2", "luogo_nasc_2")
                'pdf.SetCampo("prov_nasc_3", "prov_nasc_3")
                'pdf.SetCampo("cognome_12", "cognome_12")
                'pdf.SetCampo("nome_3", "nome_3")
                'pdf.SetCampo("data_nasc_14", "data_nasc_14")
                'pdf.SetCampo("info_15e", "info_15e")
                'pdf.SetCampo("luogo_nasc_5", "luogo_nasc_5")
                'pdf.SetCampo("nome_con", "nome_con")
                'pdf.SetCampo("cod_fisc_14", "cod_fisc_14")
                'pdf.SetCampo("prov_resid_14", "prov_resid_14")
                'pdf.SetCampo("cod_fisc_5", "cod_fisc_5")
                'pdf.SetCampo("prov_resid_11", "prov_resid_11")
                'pdf.SetCampo("prov_resid_12", "prov_resid_12")
                'pdf.SetCampo("prov_resid_13", "prov_resid_13")

                pdf.Compile()

                pdf.Dispose()



                'My.Computer.FileSystem.CopyFile(.NomeFileModello, Prestazione.FileOutPut)
            End If
        End With



    End Sub

    Private Function RetrieveSesso(ByVal Prest As Prestazione) As String


        If Prest.Utente.Sesso = AbstractPersona.Sex.Maschio Then
            Return "M"
        End If

        Return "F"


        'If Prest.Utente.Sesso.ToString().Equals("Maschio") = True Then
        'End If
    End Function

End Class

