Imports WIN.TECHNICAL.PDF_PRINTER
Imports System.Runtime.InteropServices

Public Class PdfCompilerANFGESTSEP
    Implements IDocumentCreatorAdapter

    Private pdf As PdfCompiler
    Private tp As TipoPrestazione
    Private fileInput As String
    Private fileOutput As String
    <DllImport("kernel32.dll", SetLastError:=True)> _
    Public Shared Function LoadLibrary(ByVal lpFileName As String) As IntPtr
    End Function

    Public Sub CreateDocument(ByVal Prestazione As Prestazione) Implements IDocumentCreatorAdapter.CreateDocument
        Dim m_TipoPrestazione As TipoPrestazione = CType(Prestazione.TipoPrestazione, TipoPrestazione)

        With m_TipoPrestazione
            If .FileModelloExist Then

                Prestazione.SetFileOutput(.GetFileOutputName(Prestazione.Utente))

                tp = Prestazione.TipoPrestazione()
                fileInput = tp.NomeFileModello
                fileOutput = Prestazione.FileOutPut
                pdf = New PdfCompiler(fileInput, fileOutput)
                pdf.Setup()
                'pdf.SetCampo("Anome", "anome")
                'pdf.SetCampo("Acognome", Prestazione.Utente.Cognome)

                'pdf.SetCampo("Acodfisc", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("Acognome coniuge", "")
                'pdf.SetCampo("Adatanascita", Prestazione.Utente.DataNascita)
                'pdf.SetCampo("A_M/F", RetrieveSesso(Prestazione))
                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)

                'pdf.SetCampo("Acomune nascita", Prestazione.Utente.ComuneNascita.Descrizione)

                'pdf.SetCampo("Aprovnascita", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("Acittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("Acomuneresidenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("Aindirizzoresidenza", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("Aprovresidenza", Prestazione.Utente.Residenza.Provincia.Sigla)
                'pdf.SetCampo("Acapresidenza", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("telefono", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("email", Prestazione.Utente.Comunicazione.Mail)
                'pdf.SetCampo("sede inps", "")
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)
                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)

                '******************************************
                pdf.SetCampo("Anome", Prestazione.Utente.Nome)
                pdf.SetCampo("Acognome", Prestazione.Utente.Cognome)
                'pdf.SetCampo("Acodfisc", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("Acognome_coniuge", "Acognome coniuge")
                pdf.SetCampo("Adatanascita", Prestazione.Utente.DataNascita)
                pdf.SetCampo("A_M/F", RetrieveSesso(Prestazione))
                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)
                pdf.SetCampo("Acomune nascita", Prestazione.Utente.ComuneNascita.Descrizione)
                pdf.SetCampo("Aprovnascita", Prestazione.Utente.ProvinciaNascita.Sigla)
                pdf.SetCampo("Acittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                pdf.SetCampo("Acomuneresidenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                pdf.SetCampo("Aindirizzoresidenza", Prestazione.Utente.Residenza.Via)
                pdf.SetCampo("Aprovresidenza", Prestazione.Utente.Residenza.Provincia.Sigla)
                pdf.SetCampo("Acapresidenza", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("telefono", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("email", Prestazione.Utente.Comunicazione.Mail)
                pdf.SetCampo("sede inps", Prestazione.Utente.Segreteria.Comune)
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)
                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)




                'pdf.SetCampo("ric_8", "ric_8")
                'pdf.SetCampo("F_O/A", "F_O/A")
                'pdf.SetCampo("G_CODICE_FISCALE", "G_CODICE_FISCALE")
                'pdf.SetCampo("Gdata", "Gdata")
                'pdf.SetCampo("Aindirizzoresidenza", "Aindirizzoresidenza")
                'pdf.SetCampo("Aprovresidenza", "Aprovresidenza")
                'pdf.SetCampo("E2_tot", "E2_tot")
                'pdf.SetCampo("G_num civ", "G_num civ")
                'pdf.SetCampo("Ddatanascita_.6", "Ddatanascita_.6")
                'pdf.SetCampo("E_anno 1bis", "E_anno 1bis")
                'pdf.SetCampo("F_IL", "F_IL")
                'pdf.SetCampo("G_PROV/res", "G_PROV/res")
                'pdf.SetCampo("E1_tot", "E1_tot")
                'pdf.SetCampo("E_anno 2bis", "E_anno 2bis")
                'pdf.SetCampo("Ddatanascita_.3", "Ddatanascita_.3")
                'pdf.SetCampo("F_ai punti", "F_ai punti")
                'pdf.SetCampo("Anome_echo", "Anome_echo")
                'pdf.SetCampo("Aprovnascita", "Aprovnascita")
                'pdf.SetCampo("D_codfisc_.6", "D_codfisc_.6")
                'pdf.SetCampo("E2_redd 5", "E2_redd 5")
                'pdf.SetCampo("E2_redd 4", "E2_redd 4")
                'pdf.SetCampo("E2_redd 7", "E2_redd 7")
                'pdf.SetCampo("I_comunic 3", "I_comunic 3")
                'pdf.SetCampo("E2_redd 1", "E2_redd 1")
                'pdf.SetCampo("G_DATA_NASC", "G_DATA_NASC")
                'pdf.SetCampo("E2_redd 3", "E2_redd 3")
                'pdf.SetCampo("Drapp/par_.1", "Drapp/par_.1")
                'pdf.SetCampo("Drapp/par_.5", "Drapp/par_.5")
                'pdf.SetCampo("E1_redd 3", "E1_redd 3")
                'pdf.SetCampo("periodo dal", "periodo dal")
                'pdf.SetCampo("E_anno 1", "E_anno 1")
                'pdf.SetCampo("I_comunic 1", "I_comunic 1")
                'pdf.SetCampo("sede inps", "sede inps")
                'pdf.SetCampo("Acomuneresidenza", "Acomuneresidenza")
                'pdf.SetCampo("E1_redd 8", "E1_redd 8")
                'pdf.SetCampo("Dcomune nasc_.1", "Dcomune nasc_.1")
                'pdf.SetCampo("D_codfisc_.3", "D_codfisc_.3")
                'pdf.SetCampo("H_O/A", "H_O/A")
                'pdf.SetCampo("PIN", "PIN")
                'pdf.SetCampo("H_LA", "H_LA")
                'pdf.SetCampo("G_cognome", "G_cognome")
                'pdf.SetCampo("protocollo", "protocollo")
                'pdf.SetCampo("G_INDIRIZZO", "G_INDIRIZZO")
                'pdf.SetCampo("ric_9 n", "ric_9 n")
                'pdf.SetCampo("E1_redd 5", "E1_redd 5")
                'pdf.SetCampo("E1_redd 4", "E1_redd 4")
                'pdf.SetCampo("Acapresidenza", "Acapresidenza")
                'pdf.SetCampo("Fdata", "Fdata")
                'pdf.SetCampo("E2_totale", "E2_totale")
                'pdf.SetCampo("Ddatanascita_.7", "Ddatanascita_.7")
                'pdf.SetCampo("sede inps_echo", "sede inps_echo")
                'pdf.SetCampo("E1_totale", "E1_totale")
                'pdf.SetCampo("Dcomune nasc_.2", "Dcomune nasc_.2")
                'pdf.SetCampo("ric_5 n", "ric_5 n")
                'pdf.SetCampo("Anome", "Anome")
                'pdf.SetCampo("E2_redd 6", "E2_redd 6")
                'pdf.SetCampo("D_codfisc_.5", "D_codfisc_.5")
                'pdf.SetCampo("D_cogn/nom_.6", "D_cogn/nom_.6")
                'pdf.SetCampo("D_cogn/nom_.7", "D_cogn/nom_.7")
                'pdf.SetCampo("G_COMUNE/res", "G_COMUNE/res")
                'pdf.SetCampo("CAB", "CAB")
                'pdf.SetCampo("D_codfisc_.8", "D_codfisc_.8")
                'pdf.SetCampo("Drapp/par_.6", "Drapp/par_.6")
                'pdf.SetCampo("D_codfisc_.1", "D_codfisc_.1")
                'pdf.SetCampo("Bemolum", "Bemolum")
                'pdf.SetCampo("Ddatanascita_.8", "Ddatanascita_.8")
                'pdf.SetCampo("F_LA", "F_LA")
                'pdf.SetCampo("Dcomune nasc_.8", "Dcomune nasc_.8")
                'pdf.SetCampo("inf", "inf")
                'pdf.SetCampo("I_comunic", "I_comunic")
                'pdf.SetCampo("Acittadinanza", "Acittadinanza")
                'pdf.SetCampo("F_num prat", "F_num prat")
                'pdf.SetCampo("A_M/F", "A_M/F")
                'pdf.SetCampo("CIN", "CIN")
                'pdf.SetCampo("Ddatanascita_.4", "Ddatanascita_.4")
                'pdf.SetCampo("inf  4", "inf  4")
                'pdf.SetCampo("Bdataiscr", "Bdataiscr")
                'pdf.SetCampo("G_COMUNE/nasc", "G_COMUNE/nasc")
                'pdf.SetCampo("D_cogn/nom_.1", "D_cogn/nom_.1")
                'pdf.SetCampo("periodo al", "periodo al")
                'pdf.SetCampo("D_cogn/nom_.3", "D_cogn/nom_.3")
                'pdf.SetCampo("dataversione", "dataversione")
                'pdf.SetCampo("Ddatanascita_.1", "Ddatanascita_.1")
                'pdf.SetCampo("Dcomune nasc_.3", "Dcomune nasc_.3")
                'pdf.SetCampo("G_M/F", "G_M/F")
                'pdf.SetCampo("Ddatanascita_.5", "Ddatanascita_.5")
                'pdf.SetCampo("E2_tot 369", "E2_tot 369")
                'pdf.SetCampo("Acognome", "Acognome")
                'pdf.SetCampo("E1_tot 123", "E1_tot 123")
                'pdf.SetCampo("D_codfisc_.4", "D_codfisc_.4")
                'pdf.SetCampo("Acomune nascita", "Acomune nascita")
                'pdf.SetCampo("Dcomune nasc_.4", "Dcomune nasc_.4")
                'pdf.SetCampo("Drapp/par_.2", "Drapp/par_.2")
                'pdf.SetCampo("Acognome_coniuge", "Acognome_coniuge")
                'pdf.SetCampo("G_TELEFONO", "G_TELEFONO")
                'pdf.SetCampo("Drapp/par_.7", "Drapp/par_.7")
                'pdf.SetCampo("descrizione", "descrizione")
                'pdf.SetCampo("Dcomune nasc_.7", "Dcomune nasc_.7")
                'pdf.SetCampo("H_IL", "H_IL")
                'pdf.SetCampo("Hdata", "Hdata")
                'pdf.SetCampo("F_patronato", "F_patronato")
                'pdf.SetCampo("E1_tot 147", "E1_tot 147")
                'pdf.SetCampo("G_CITTADINANZA", "G_CITTADINANZA")
                'pdf.SetCampo("Dcomune nasc_.6", "Dcomune nasc_.6")
                'pdf.SetCampo("E1_redd 7", "E1_redd 7")
                'pdf.SetCampo("ABI", "ABI")
                'pdf.SetCampo("E1_redd 1", "E1_redd 1")
                'pdf.SetCampo("Ddatanascita_.2", "Ddatanascita_.2")
                'pdf.SetCampo("E1_redd 2", "E1_redd 2")
                'pdf.SetCampo("inf  1", "inf  1")
                'pdf.SetCampo("Acognome_echo", "Acognome_echo")
                'pdf.SetCampo("D_cogn/nom_.8", "D_cogn/nom_.8")
                'pdf.SetCampo("E1_redd 9", "E1_redd 9")
                'pdf.SetCampo("E2_redd 2", "E2_redd 2")
                'pdf.SetCampo("G_nome", "G_nome")
                'pdf.SetCampo("E2_redd 9", "E2_redd 9")
                'pdf.SetCampo("E2_redd 8", "E2_redd 8")
                'pdf.SetCampo("D_cogn/nom_.2", "D_cogn/nom_.2")
                'pdf.SetCampo("G_CAP", "G_CAP")
                'pdf.SetCampo("D_cogn/nom_.4", "D_cogn/nom_.4")
                'pdf.SetCampo("D_cogn/nom_.5", "D_cogn/nom_.5")
                'pdf.SetCampo("Dcomune nasc_.5", "Dcomune nasc_.5")
                'pdf.SetCampo("Btotale", "Btotale")
                'pdf.SetCampo("G_PROV/nasc", "G_PROV/nasc")
                'pdf.SetCampo("E2_tot 789", "E2_tot 789")
                'pdf.SetCampo("E1_redd 6", "E1_redd 6")
                'pdf.SetCampo("E1_tot 369", "E1_tot 369")
                'pdf.SetCampo("D_codfisc_.7", "D_codfisc_.7")
                'pdf.SetCampo("G_DATA", "G_DATA")
                'pdf.SetCampo("Drapp/par_.3", "Drapp/par_.3")
                'pdf.SetCampo("E2_tot 258", "E2_tot 258")
                'pdf.SetCampo("D_codfisc_.2", "D_codfisc_.2")
                'pdf.SetCampo("nomefile", "nomefile")
                'pdf.SetCampo("Drapp/par_.4", "Drapp/par_.4")
                'pdf.SetCampo("Drapp/par_.8", "Drapp/par_.8")
                'pdf.SetCampo("E_anno 2", "E_anno 2")
                'pdf.SetCampo("cod/cli", "cod/cli")
                'pdf.SetCampo("inf  3", "inf  3")
                'pdf.SetCampo("ric_4 n", "ric_4 n")
                'pdf.SetCampo("Adatanascita", "Adatanascita")
                'pdf.SetCampo("ric_6 n", "ric_6 n")
                'pdf.SetCampo("ric_7 n", "ric_7 n")
                'pdf.SetCampo("ric_1 n", "ric_1 n")
                'pdf.SetCampo("ric_2 n", "ric_2 n")
                'pdf.SetCampo("ric_3 n ", "ric_3 n ")
                'pdf.SetCampo("pag4", "pag4")
                'pdf.SetCampo("pag3", "pag3")

                pdf.Compile()

                pdf.Dispose()



                'My.Computer.FileSystem.CopyFile(.NomeFileModello, Prestazione.FileOutPut)
            End If
        End With



    End Sub

    Private Function RetrieveSesso(ByVal Prest As Prestazione) As String


        If Prest.Utente.Sesso = AbstractPersona.Sex.Maschio Then
            Return "M"
        End If

        Return "F"


        'If Prest.Utente.Sesso.ToString().Equals("Maschio") = True Then
        'End If
    End Function

End Class