Imports WIN.TECHNICAL.PDF_PRINTER
Imports System.Runtime.InteropServices
Imports System.IO

Public Class PdfCompilerSetting12
    Implements IDocumentCreatorAdapter

    Private pdf As PdfCompiler
    Private tp As TipoPrestazione
    Private fileInput As String
    Private fileOutput As String
    <DllImport("kernel32.dll", SetLastError:=True)> _
    Public Shared Function LoadLibrary(ByVal lpFileName As String) As IntPtr
    End Function

    Public Sub CreateDocument(ByVal Prestazione As Prestazione) Implements IDocumentCreatorAdapter.CreateDocument
        Dim m_TipoPrestazione As TipoPrestazione = CType(Prestazione.TipoPrestazione, TipoPrestazione)

        With m_TipoPrestazione
            If .FileModelloExist Then

                Prestazione.SetFileOutput(.GetFileOutputName(Prestazione.Utente))

                tp = Prestazione.TipoPrestazione()
                fileInput = tp.NomeFileModello
                fileOutput = Prestazione.FileOutPut
                If (Environment.Version.Major >= 4) Then
                    Dim folder As String = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "..\Microsoft.NET\Framework\v2.0.50727")

                    folder = Path.GetFullPath(folder)

                    LoadLibrary(Path.Combine(folder, "vjsnativ.dll"))
                End If
                pdf = New PdfCompiler(fileInput, fileOutput)
                pdf.Setup()
                'pdf.SetCampo("nome", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("cognome coniuge", "")
                'pdf.SetCampo("datanascita", Prestazione.Utente.DataNascita)
                'pdf.SetCampo("M/F", RetrieveSesso(Prestazione))
                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)

                'pdf.SetCampo("comune nascita", Prestazione.Utente.ComuneNascita.Descrizione)

                'pdf.SetCampo("provnascita", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("cittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("comuneresidenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("indirizzoresidenza", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("provresidenza", Prestazione.Utente.Residenza.Provincia.Sigla)
                'pdf.SetCampo("capresidenza", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("telefono", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("email", Prestazione.Utente.Comunicazione.Mail)
                'pdf.SetCampo("sede inps", "")
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)
                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)


                ''''''''''''''''''''''''''*******************************************
                pdf.SetCampo("cognome", Prestazione.Utente.Cognome)
                pdf.SetCampo("nome", Prestazione.Utente.Nome)
                pdf.SetCampo("codfisc", Prestazione.Utente.CodiceFiscale)
                pdf.SetCampo("sesso", RetrieveSesso(Prestazione))
                pdf.SetCampo("datanascita", Prestazione.Utente.DataNascita)
                pdf.SetCampo("comune nascita", Prestazione.Utente.ComuneNascita.Descrizione)
                pdf.SetCampo("provnascita", Prestazione.Utente.ProvinciaNascita.Sigla)
                pdf.SetCampo("indirizzoresidenza", Prestazione.Utente.Residenza.Via)
                pdf.SetCampo("comuneresidenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                pdf.SetCampo("provresidenza", Prestazione.Utente.Residenza.Provincia.Sigla)


                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("cittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("capresidenza", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("telefono", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("email", Prestazione.Utente.Comunicazione.Mail)
                'pdf.SetCampo("sede inps", "")
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)
                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)


                'pdf.SetCampo("E/APR_.9", "E/APR_.9")
                'pdf.SetCampo("B2", "B2")
                'pdf.SetCampo("F2", "F2")
                'pdf.SetCampo("E/APR_.1", "E/APR_.1")
                'pdf.SetCampo("E/APR_.24", "E/APR_.24")
                'pdf.SetCampo("E/APR_.27", "E/APR_.27")
                'pdf.SetCampo("E/APR_.26", "E/APR_.26")
                'pdf.SetCampo("E/APR_.29", "E/APR_.29")
                'pdf.SetCampo("E/APR_.28", "E/APR_.28")
                'pdf.SetCampo("E/NOV_.22", "E/NOV_.22")
                'pdf.SetCampo("E/FEBB_.31", "E/FEBB_.31")
                'pdf.SetCampo("E/FEBB_.21", "E/FEBB_.21")
                'pdf.SetCampo("E/APR_.21", "E/APR_.21")
                'pdf.SetCampo("E/APR_.20", "E/APR_.20")
                'pdf.SetCampo("E/APR_.23", "E/APR_.23")
                'pdf.SetCampo("E/APR_.22", "E/APR_.22")
                'pdf.SetCampo("E/APR_.25", "E/APR_.25")
                'pdf.SetCampo("E/SETT_.31", "E/SETT_.31")
                'pdf.SetCampo("E/SETT_.21", "E/SETT_.21")
                'pdf.SetCampo("E/SETT_.11", "E/SETT_.11")
                'pdf.SetCampo("E/NOV_.4", "E/NOV_.4")
                'pdf.SetCampo("qualifica 2", "qualifica 2")
                'pdf.SetCampo("E/SETT_.15", "E/SETT_.15")
                'pdf.SetCampo("E/GENN_.12", "E/GENN_.12")
                'pdf.SetCampo("E/GENN_.22", "E/GENN_.22")
                'pdf.SetCampo("M", "M")
                'pdf.SetCampo("E/DIC_.1", "E/DIC_.1")
                'pdf.SetCampo("A", "A")
                'pdf.SetCampo("B", "B")
                'pdf.SetCampo("C", "C")
                'pdf.SetCampo("D", "D")
                'pdf.SetCampo("E/MAG_.8", "E/MAG_.8")
                'pdf.SetCampo("G", "G")
                'pdf.SetCampo("E/DIC_.9", "E/DIC_.9")
                'pdf.SetCampo("E/SETT_.28", "E/SETT_.28")
                'pdf.SetCampo("D dal 3", "D dal 3")
                'pdf.SetCampo("E/GIU_.3", "E/GIU_.3")
                'pdf.SetCampo("D al 4", "D al 4")
                'pdf.SetCampo("E/MAG_.24", "E/MAG_.24")
                'pdf.SetCampo("E/MAG_.25", "E/MAG_.25")
                'pdf.SetCampo("E/MAR_.8", "E/MAR_.8")
                'pdf.SetCampo("E/MAG_.27", "E/MAG_.27")
                'pdf.SetCampo("E/MAG_.20", "E/MAG_.20")
                'pdf.SetCampo("E/MAG_.21", "E/MAG_.21")
                'pdf.SetCampo("E/MAG_.22", "E/MAG_.22")
                'pdf.SetCampo("E/MAG_.23", "E/MAG_.23")
                'pdf.SetCampo("E/MAG_.7", "E/MAG_.7")
                'pdf.SetCampo("E/MAG_.28", "E/MAG_.28")
                'pdf.SetCampo("E/MAG_.29", "E/MAG_.29")
                'pdf.SetCampo("E/LUG_.15", "E/LUG_.15")
                'pdf.SetCampo("E/LUG_.14", "E/LUG_.14")
                'pdf.SetCampo("E/LUG_.17", "E/LUG_.17")
                'pdf.SetCampo("E/LUG_.16", "E/LUG_.16")
                'pdf.SetCampo("E/LUG_.7", "E/LUG_.7")
                'pdf.SetCampo("E/LUG_.10", "E/LUG_.10")
                'pdf.SetCampo("E/LUG_.11", "E/LUG_.11")
                'pdf.SetCampo("E/LUG_.12", "E/LUG_.12")
                'pdf.SetCampo("E/LUG_.13", "E/LUG_.13")
                'pdf.SetCampo("E/OTT_.8", "E/OTT_.8")
                'pdf.SetCampo("G_dal2", "G_dal2")
                'pdf.SetCampo("E/OTT_.7", "E/OTT_.7")
                'pdf.SetCampo("E/OTT_.6", "E/OTT_.6")
                'pdf.SetCampo("E/LUG_.18", "E/LUG_.18")
                'pdf.SetCampo("E/LUG_.19", "E/LUG_.19")
                'pdf.SetCampo("E/MAR_.7", "E/MAR_.7")
                'pdf.SetCampo("tipo contr 5", "tipo contr 5")
                'pdf.SetCampo("E/SETT_.16", "E/SETT_.16")
                'pdf.SetCampo("E/APR_.6", "E/APR_.6")
                'pdf.SetCampo("E/DIC_.11", "E/DIC_.11")
                'pdf.SetCampo("E/GENN_.17", "E/GENN_.17")
                'pdf.SetCampo("comuneresidenza", "comuneresidenza")
                'pdf.SetCampo("E/DIC_.15", "E/DIC_.15")
                'pdf.SetCampo("E/GENN_.27", "E/GENN_.27")
                'pdf.SetCampo("E/NOV_.12", "E/NOV_.12")
                'pdf.SetCampo("matr inps azienda", "matr inps azienda")
                'pdf.SetCampo("E/APR_.31", "E/APR_.31")
                'pdf.SetCampo("E/APR_.30", "E/APR_.30")
                'pdf.SetCampo("E/FEBB_.24", "E/FEBB_.24")
                'pdf.SetCampo("N20", "N20")
                'pdf.SetCampo("E/OTT_.17", "E/OTT_.17")
                'pdf.SetCampo("E/OTT_.16", "E/OTT_.16")
                'pdf.SetCampo("dataversione", "dataversione")
                'pdf.SetCampo("E/DIC_.6", "E/DIC_.6")
                'pdf.SetCampo("E/NOV_.3", "E/NOV_.3")
                'pdf.SetCampo("E/FEBB_.13", "E/FEBB_.13")
                'pdf.SetCampo("G20", "G20")
                'pdf.SetCampo("E/OTT_.10", "E/OTT_.10")
                'pdf.SetCampo("E/OTT_.15", "E/OTT_.15")
                'pdf.SetCampo("E/OTT_.14", "E/OTT_.14")
                'pdf.SetCampo("E/AGO_.6", "E/AGO_.6")
                'pdf.SetCampo("E/OTT_.12", "E/OTT_.12")
                'pdf.SetCampo("E/OTT_.11", "E/OTT_.11")
                'pdf.SetCampo("E/OTT_.19", "E/OTT_.19")
                'pdf.SetCampo("E/OTT_.18", "E/OTT_.18")
                'pdf.SetCampo("E/GIU_.16", "E/GIU_.16")
                'pdf.SetCampo("E/GIU_.17", "E/GIU_.17")
                'pdf.SetCampo("csc", "csc")
                'pdf.SetCampo("E/DIC_.30", "E/DIC_.30")
                'pdf.SetCampo("E/GIU_.12", "E/GIU_.12")
                'pdf.SetCampo("E/GIU_.13", "E/GIU_.13")
                'pdf.SetCampo("E/GIU_.10", "E/GIU_.10")
                'pdf.SetCampo("E/GIU_.11", "E/GIU_.11")
                'pdf.SetCampo("E/GIU_.29", "E/GIU_.29")
                'pdf.SetCampo("E/OTT_.9", "E/OTT_.9")
                'pdf.SetCampo("E/DIC_.8", "E/DIC_.8")
                'pdf.SetCampo("E/GIU_.18", "E/GIU_.18")
                'pdf.SetCampo("E/GIU_.19", "E/GIU_.19")
                'pdf.SetCampo("E/OTT_.13", "E/OTT_.13")
                'pdf.SetCampo("E/FEBB_.27", "E/FEBB_.27")
                'pdf.SetCampo("E/GIU_.2", "E/GIU_.2")
                'pdf.SetCampo("E/MAG_.3", "E/MAG_.3")
                'pdf.SetCampo("E/GIU_.14", "E/GIU_.14")
                'pdf.SetCampo("descrizione", "descrizione")
                'pdf.SetCampo("E/SETT_.23", "E/SETT_.23")
                'pdf.SetCampo("E/SETT_.13", "E/SETT_.13")
                'pdf.SetCampo("E/OTT_.5", "E/OTT_.5")
                'pdf.SetCampo("E/OTT_.4", "E/OTT_.4")
                'pdf.SetCampo("E/GENN_.19", "E/GENN_.19")
                'pdf.SetCampo("pag 2 gignor", "pag 2 gignor")
                'pdf.SetCampo("E/GENN_.10", "E/GENN_.10")
                'pdf.SetCampo("E/MAR_.3", "E/MAR_.3")
                'pdf.SetCampo("E/GENN_.30", "E/GENN_.30")
                'pdf.SetCampo("E/GENN_.20", "E/GENN_.20")
                'pdf.SetCampo("E/SETT_.26", "E/SETT_.26")
                'pdf.SetCampo("E/LUG_.6", "E/LUG_.6")
                'pdf.SetCampo("Z nascosto", "Z nascosto")
                'pdf.SetCampo("E/GENN_.9", "E/GENN_.9")
                'pdf.SetCampo("E/GENN_.8", "E/GENN_.8")
                'pdf.SetCampo("Z3", "Z3")
                'pdf.SetCampo("E/GENN_.5", "E/GENN_.5")
                'pdf.SetCampo("E/GENN_.4", "E/GENN_.4")
                'pdf.SetCampo("E/GENN_.7", "E/GENN_.7")
                'pdf.SetCampo("E/GENN_.6", "E/GENN_.6")
                'pdf.SetCampo("E/GENN_.1", "E/GENN_.1")
                'pdf.SetCampo("E/GENN_.3", "E/GENN_.3")
                'pdf.SetCampo("E/GENN_.2", "E/GENN_.2")
                'pdf.SetCampo("G_dal", "G_dal")
                'pdf.SetCampo("codicea", "codicea")
                'pdf.SetCampo("H3", "H3")
                'pdf.SetCampo("I3", "I3")
                'pdf.SetCampo("E/APR_.7", "E/APR_.7")
                'pdf.SetCampo("L3", "L3")
                'pdf.SetCampo("M3", "M3")
                'pdf.SetCampo("E/GIU_.15", "E/GIU_.15")
                'pdf.SetCampo("anno", "anno")
                'pdf.SetCampo("A3", "A3")
                'pdf.SetCampo("B3", "B3")
                'pdf.SetCampo("C3", "C3")
                'pdf.SetCampo("D3", "D3")
                'pdf.SetCampo("E3", "E3")
                'pdf.SetCampo("F3", "F3")
                'pdf.SetCampo("G3", "G3")
                'pdf.SetCampo("N3", "N3")
                'pdf.SetCampo("cognome", "cognome")
                'pdf.SetCampo("E/FEBB_.19", "E/FEBB_.19")
                'pdf.SetCampo("PIN", "PIN")
                'pdf.SetCampo("E/NOV_.2", "E/NOV_.2")
                'pdf.SetCampo("E/DIC_.28", "E/DIC_.28")
                'pdf.SetCampo("E/GENN_.15", "E/GENN_.15")
                'pdf.SetCampo("E/GENN_.25", "E/GENN_.25")
                'pdf.SetCampo("E/AGO_.5", "E/AGO_.5")
                'pdf.SetCampo("E/DIC_.29", "E/DIC_.29")
                'pdf.SetCampo("E/DIC_.20", "E/DIC_.20")
                'pdf.SetCampo("E/DIC_.21", "E/DIC_.21")
                'pdf.SetCampo("E/DIC_.23", "E/DIC_.23")
                'pdf.SetCampo("E/DIC_.31", "E/DIC_.31")
                'pdf.SetCampo("D dal 5", "D dal 5")
                'pdf.SetCampo("E/DIC_.22", "E/DIC_.22")
                'pdf.SetCampo("E/GIU_.5", "E/GIU_.5")
                'pdf.SetCampo("E/DIC_.24", "E/DIC_.24")
                'pdf.SetCampo("E/DIC_.25", "E/DIC_.25")
                'pdf.SetCampo("E/DIC_.26", "E/DIC_.26")
                'pdf.SetCampo("E/DIC_.27", "E/DIC_.27")
                'pdf.SetCampo("E/MAG_.2", "E/MAG_.2")
                'pdf.SetCampo("E/LUG_.9", "E/LUG_.9")
                'pdf.SetCampo("Z", "Z")
                'pdf.SetCampo("C_giorni_2", "C_giorni_2")
                'pdf.SetCampo("E/LUG_.1", "E/LUG_.1")
                'pdf.SetCampo("cognomedel marito", "cognomedel marito")
                'pdf.SetCampo("D si/no 4", "D si/no 4")
                'pdf.SetCampo("H", "H")
                'pdf.SetCampo("E/MAR_.2", "E/MAR_.2")
                'pdf.SetCampo("D si/no 1", "D si/no 1")
                'pdf.SetCampo("D si/no 5", "D si/no 5")
                'pdf.SetCampo("D si/no 3", "D si/no 3")
                'pdf.SetCampo("D si/no 2", "D si/no 2")
                'pdf.SetCampo("N", "N")
                'pdf.SetCampo("E/LUG_.30", "E/LUG_.30")
                'pdf.SetCampo("E/LUG_.31", "E/LUG_.31")
                'pdf.SetCampo("E/MAR_.19", "E/MAR_.19")
                'pdf.SetCampo("E/MAR_.18", "E/MAR_.18")
                'pdf.SetCampo("E", "E")
                'pdf.SetCampo("F", "F")
                'pdf.SetCampo("E/FEBB_.29", "E/FEBB_.29")
                'pdf.SetCampo("E/MAR_.11", "E/MAR_.11")
                'pdf.SetCampo("E/MAR_.10", "E/MAR_.10")
                'pdf.SetCampo("E/MAR_.13", "E/MAR_.13")
                'pdf.SetCampo("E/SETT_.29", "E/SETT_.29")
                'pdf.SetCampo("E/SETT_.19", "E/SETT_.19")
                'pdf.SetCampo("E/MAR_.14", "E/MAR_.14")
                'pdf.SetCampo("E/MAR_.17", "E/MAR_.17")
                'pdf.SetCampo("E/MAR_.16 ", "E/MAR_.16")
                'pdf.SetCampo("E/SETT_.25", "E/SETT_.25")
                'pdf.SetCampo("C_dataassunz", "C_dataassunz")
                'pdf.SetCampo("tipo contr 3", "tipo contr 3")
                'pdf.SetCampo("simb", "simb")
                'pdf.SetCampo("E/APR_.4", "E/APR_.4")
                'pdf.SetCampo("provresidenza", "provresidenza")
                'pdf.SetCampo("D al 5", "D al 5")
                'pdf.SetCampo("qualifica 5", "qualifica 5")
                'pdf.SetCampo("D al 2", "D al 2")
                'pdf.SetCampo("E/APR_.19", "E/APR_.19")
                'pdf.SetCampo("E/APR_.18", "E/APR_.18")
                'pdf.SetCampo("Z20", "Z20")
                'pdf.SetCampo("Z1", "Z1")
                'pdf.SetCampo("E/APR_.11", "E/APR_.11")
                'pdf.SetCampo("E/APR_.10", "E/APR_.10")
                'pdf.SetCampo("E/APR_.13", "E/APR_.13")
                'pdf.SetCampo("E/APR_.12", "E/APR_.12")
                'pdf.SetCampo("E/APR_.15", "E/APR_.15")
                'pdf.SetCampo("E/APR_.14", "E/APR_.14")
                'pdf.SetCampo("E/APR_.17", "E/APR_.17")
                'pdf.SetCampo("E/APR_.16", "E/APR_.16")
                'pdf.SetCampo("Z2nascosto", "Z2nascosto")
                'pdf.SetCampo("H20", "H20")
                'pdf.SetCampo("I20", "I20")
                'pdf.SetCampo("H1", "H1")
                'pdf.SetCampo("I1", "I1")
                'pdf.SetCampo("L20", "L20")
                'pdf.SetCampo("M20", "M20")
                'pdf.SetCampo("E/NOV_.1", "E/NOV_.1")
                'pdf.SetCampo("M1", "M1")
                'pdf.SetCampo("N1", "N1")
                'pdf.SetCampo("A20", "A20")
                'pdf.SetCampo("B20", "B20")
                'pdf.SetCampo("A1", "A1")
                'pdf.SetCampo("D20", "D20")
                'pdf.SetCampo("E20", "E20")
                'pdf.SetCampo("F20", "F20")
                'pdf.SetCampo("E1", "E1")
                'pdf.SetCampo("F1", "F1")
                'pdf.SetCampo("G1", "G1")
                'pdf.SetCampo("E/DIC_.2", "E/DIC_.2")
                'pdf.SetCampo("E/MAG_.5", "E/MAG_.5")
                'pdf.SetCampo("E/GIU_.4", "E/GIU_.4")
                'pdf.SetCampo("E/GIU_.31", "E/GIU_.31")
                'pdf.SetCampo("E/FEBB_.22", "E/FEBB_.22")
                'pdf.SetCampo("E/NOV_.31", "E/NOV_.31")
                'pdf.SetCampo("E/NOV_.30", "E/NOV_.30")
                'pdf.SetCampo("E/LUG_.8", "E/LUG_.8")
                'pdf.SetCampo("E/MAR_.5", "E/MAR_.5")
                'pdf.SetCampo("I", "I")
                'pdf.SetCampo("E/NOV_.9", "E/NOV_.9")
                'pdf.SetCampo("E/GENN_.13", "E/GENN_.13")
                'pdf.SetCampo("C_motivo", "C_motivo")
                'pdf.SetCampo("E/GENN_.23", "E/GENN_.23")
                'pdf.SetCampo("E/LUG_.24", "E/LUG_.24")
                'pdf.SetCampo("E/LUG_.25", "E/LUG_.25")
                'pdf.SetCampo("E/LUG_.26", "E/LUG_.26")
                'pdf.SetCampo("E/LUG_.27", "E/LUG_.27")
                'pdf.SetCampo("E/LUG_.20", "E/LUG_.20")
                'pdf.SetCampo("E/LUG_.21", "E/LUG_.21")
                'pdf.SetCampo("E/LUG_.22", "E/LUG_.22")
                'pdf.SetCampo("E/LUG_.23", "E/LUG_.23")
                'pdf.SetCampo("E/LUG_.28", "E/LUG_.28")
                'pdf.SetCampo("E/LUG_.29", "E/LUG_.29")
                'pdf.SetCampo("tipo contr 4", "tipo contr 4")
                'pdf.SetCampo("E/MAR_.12", "E/MAR_.12")
                'pdf.SetCampo("E/MAR_.15", "E/MAR_.15")
                'pdf.SetCampo("sesso", "sesso")
                'pdf.SetCampo("E/SETT_.27", "E/SETT_.27")
                'pdf.SetCampo("tipo contr 2", "tipo contr 2")
                'pdf.SetCampo("provnascita", "provnascita")
                'pdf.SetCampo("E/NOV_.7", "E/NOV_.7")
                'pdf.SetCampo("G/anno_2", "G/anno_2")
                'pdf.SetCampo("Z3nascosto", "Z3nascosto")
                'pdf.SetCampo("codfisc_echo", "codfisc_echo")
                'pdf.SetCampo("E/FEBB_.15", "E/FEBB_.15")
                'pdf.SetCampo("E/FEBB_.25", "E/FEBB_.25")
                'pdf.SetCampo("E/NOV_.8", "E/NOV_.8")
                'pdf.SetCampo("protocollo", "protocollo")
                'pdf.SetCampo("E/SETT_.17", "E/SETT_.17")
                'pdf.SetCampo("E/GENN_.18", "E/GENN_.18")
                'pdf.SetCampo("E/AGO_.31 ", "E/AGO_.31 ")
                'pdf.SetCampo("E/GENN_.28", "E/GENN_.28")
                'pdf.SetCampo("E/DIC_.5", "E/DIC_.5")
                'pdf.SetCampo("motd5", "motd5")
                'pdf.SetCampo("motd4", "motd4")
                'pdf.SetCampo("motd3", "motd3")
                'pdf.SetCampo("motd2", "motd2")
                'pdf.SetCampo("motd1", "motd1")
                'pdf.SetCampo("E/AGO_.3", "E/AGO_.3")
                'pdf.SetCampo("E/GIU_.26", "E/GIU_.26")
                'pdf.SetCampo("E/GIU_.27", "E/GIU_.27")
                'pdf.SetCampo("E/GIU_.24", "E/GIU_.24")
                'pdf.SetCampo("E/GIU_.25", "E/GIU_.25")
                'pdf.SetCampo("E/MAG_.4", "E/MAG_.4")
                'pdf.SetCampo("E/GIU_.23", "E/GIU_.23")
                'pdf.SetCampo("E/GIU_.7", "E/GIU_.7")
                'pdf.SetCampo("E/GIU_.21", "E/GIU_.21")
                'pdf.SetCampo("E/NOV_.25", "E/NOV_.25")
                'pdf.SetCampo("E/NOV_.24", "E/NOV_.24")
                'pdf.SetCampo("E/NOV_.27", "E/NOV_.27")
                'pdf.SetCampo("E/NOV_.26", "E/NOV_.26")
                'pdf.SetCampo("E/NOV_.21", "E/NOV_.21")
                'pdf.SetCampo("E/NOV_.20", "E/NOV_.20")
                'pdf.SetCampo("E/NOV_.23", "E/NOV_.23")
                'pdf.SetCampo("E/FEBB_.9", "E/FEBB_.9")
                'pdf.SetCampo("E/FEBB_.8", "E/FEBB_.8")
                'pdf.SetCampo("E/OTT_.3", "E/OTT_.3")
                'pdf.SetCampo("E/NOV_.29", "E/NOV_.29")
                'pdf.SetCampo("E/NOV_.28", "E/NOV_.28")
                'pdf.SetCampo("E/FEBB_.1", "E/FEBB_.1")
                'pdf.SetCampo("E/MAR_.4", "E/MAR_.4")
                'pdf.SetCampo("E/FEBB_.3", "E/FEBB_.3")
                'pdf.SetCampo("E/FEBB_.2", "E/FEBB_.2")
                'pdf.SetCampo("E/FEBB_.5", "E/FEBB_.5")
                'pdf.SetCampo("E/FEBB_.4", "E/FEBB_.4")
                'pdf.SetCampo("E/FEBB_.7", "E/FEBB_.7")
                'pdf.SetCampo("E/FEBB_.6", "E/FEBB_.6")
                'pdf.SetCampo("E/LUG_.3", "E/LUG_.3")
                'pdf.SetCampo("nome_echo", "nome_echo")
                'pdf.SetCampo("E/FEBB_.10", "E/FEBB_.10")
                'pdf.SetCampo("E/FEBB_.30", "E/FEBB_.30")
                'pdf.SetCampo("E/FEBB_.20", "E/FEBB_.20")
                'pdf.SetCampo("E/MAR_.31", "E/MAR_.31")
                'pdf.SetCampo("E/MAR_.30", "E/MAR_.30")
                'pdf.SetCampo("E/SETT_.30", "E/SETT_.30")
                'pdf.SetCampo("E/SETT_.20", "E/SETT_.20")
                'pdf.SetCampo("E/SETT_.10", "E/SETT_.10")
                'pdf.SetCampo("E/FEBB_.11", "E/FEBB_.11")
                'pdf.SetCampo("tipo contr 1", "tipo contr 1")
                'pdf.SetCampo("Z20nascosto", "Z20nascosto")
                'pdf.SetCampo("E/APR_.2", "E/APR_.2")
                'pdf.SetCampo("E/GENN_.11", "E/GENN_.11")
                'pdf.SetCampo("E/GENN_.31", "E/GENN_.31")
                'pdf.SetCampo("E/GENN_.21", "E/GENN_.21")
                'pdf.SetCampo("E/SETT_.7", "E/SETT_.7")
                'pdf.SetCampo("E/SETT_.6", "E/SETT_.6")
                'pdf.SetCampo("E/SETT_.5", "E/SETT_.5")
                'pdf.SetCampo("E/SETT_.4", "E/SETT_.4")
                'pdf.SetCampo("E/SETT_.3", "E/SETT_.3")
                'pdf.SetCampo("E/SETT_.2", "E/SETT_.2")
                'pdf.SetCampo("E/SETT_.1", "E/SETT_.1")
                'pdf.SetCampo("E/SETT_.9", "E/SETT_.9")
                'pdf.SetCampo("E/SETT_.8", "E/SETT_.8")
                'pdf.SetCampo("sede inps", "sede inps")
                'pdf.SetCampo("E/OTT_.25", "E/OTT_.25")
                'pdf.SetCampo("E/OTT_.24", "E/OTT_.24")
                'pdf.SetCampo("E/OTT_.23", "E/OTT_.23")
                'pdf.SetCampo("E/GIU_.30", "	E/GIU_.30")
                'pdf.SetCampo("sedea", "sedea")
                'pdf.SetCampo("E/AGO_.28", "E/AGO_.28")
                'pdf.SetCampo("E/AGO_.29", "E/AGO_.29")
                'pdf.SetCampo("E/LUG_.2", "E/LUG_.2")
                'pdf.SetCampo("qualifica 3", "qualifica 3")
                'pdf.SetCampo("E/AGO_.24", "E/AGO_.24")
                'pdf.SetCampo("E/AGO_.25", "E/AGO_.25")
                'pdf.SetCampo("E/AGO_.26", "E/AGO_.26")
                'pdf.SetCampo("E/AGO_.27", "E/AGO_.27")
                'pdf.SetCampo("E/AGO_.20", "E/AGO_.20")
                'pdf.SetCampo("E/AGO_.21", "E/AGO_.21")
                'pdf.SetCampo("E/AGO_.22", "E/AGO_.22")
                'pdf.SetCampo("E/AGO_.23", "E/AGO_.23")
                'pdf.SetCampo("E/DIC_.4", "E/DIC_.4")
                'pdf.SetCampo("E/AGO_.2", "E/AGO_.2")
                'pdf.SetCampo("E/APR_.5", "E/APR_.5")
                'pdf.SetCampo("D dal 2", "D dal 2")
                'pdf.SetCampo("E/GIU_.6", "E/GIU_.6")
                'pdf.SetCampo("E/NOV_.15", "E/NOV_.15")
                'pdf.SetCampo("E/NOV_.14", "E/NOV_.14")
                'pdf.SetCampo("E/NOV_.17", "E/NOV_.17")
                'pdf.SetCampo("E/NOV_.16", "E/NOV_.16")
                'pdf.SetCampo("E/NOV_.11", "E/NOV_.11")
                'pdf.SetCampo("E/NOV_.10", "E/NOV_.10")
                'pdf.SetCampo("E/NOV_.13", "E/NOV_.13")
                'pdf.SetCampo("E/MAG_.12", "E/MAG_.12")
                'pdf.SetCampo("E/MAG_.13", "E/MAG_.13")
                'pdf.SetCampo("E/NOV_.19", "E/NOV_.19")
                'pdf.SetCampo("E/NOV_.18", "E/NOV_.18")
                'pdf.SetCampo("E/MAG_.19", "E/MAG_.19")
                'pdf.SetCampo("E/GENN_.16", "E/GENN_.16")
                'pdf.SetCampo("E/GENN_.26", "E/GENN_.26")
                'pdf.SetCampo("E/GIU_.22", "E/GIU_.22")
                'pdf.SetCampo("E/GIU_.20", "E/GIU_.20")
                'pdf.SetCampo("L1", "L1")
                'pdf.SetCampo("B1", "B1")
                'pdf.SetCampo("C1", "C1")
                'pdf.SetCampo("D1", "D1")
                'pdf.SetCampo("E/MAR_.29", "E/MAR_.29")
                'pdf.SetCampo("E/MAR_.28", "E/MAR_.28")
                'pdf.SetCampo("E/MAR_.21", "E/MAR_.21")
                'pdf.SetCampo("E/MAR_.20", "E/MAR_.20")
                'pdf.SetCampo("E/MAR_.23", "E/MAR_.23")
                'pdf.SetCampo("E/MAR_.22", "E/MAR_.22")
                'pdf.SetCampo("E/MAR_.25", "E/MAR_.25")
                'pdf.SetCampo("E/MAR_.24", "E/MAR_.24")
                'pdf.SetCampo("E/MAR_.27", "E/MAR_.27")
                'pdf.SetCampo("E/MAR_.26", "E/MAR_.26")
                'pdf.SetCampo("E/MAR_.9", "E/MAR_.9")
                'pdf.SetCampo("E/APR_.3", "E/APR_.3")
                'pdf.SetCampo("L", "L")
                'pdf.SetCampo("qualifica 4", "qualifica 4")
                'pdf.SetCampo("E/FEBB_.16", "E/FEBB_.16")
                'pdf.SetCampo("E/FEBB_.26", "E/FEBB_.26")
                'pdf.SetCampo("E/AGO_.7", "E/AGO_.7")
                'pdf.SetCampo("E/OTT_.27", "E/OTT_.27")
                'pdf.SetCampo("E/OTT_.26", "E/OTT_.26")
                'pdf.SetCampo("E/SETT_.22", "E/SETT_.22")
                'pdf.SetCampo("E/SETT_.12", "E/SETT_.12")
                'pdf.SetCampo("E/NOV_.6", "E/NOV_.6")
                'pdf.SetCampo("E/OTT_.22", "E/OTT_.22")
                'pdf.SetCampo("E/OTT_.21", "E/OTT_.21")
                'pdf.SetCampo("E/OTT_.20", "E/OTT_.20")
                'pdf.SetCampo("E/AGO_.18", "E/AGO_.18")
                'pdf.SetCampo("E/AGO_.19", "E/AGO_.19")
                'pdf.SetCampo("C_datalicenz", "C_datalicenz")
                'pdf.SetCampo("E/AGO_.14", "E/AGO_.14")
                'pdf.SetCampo("E/OTT_.2", "E/OTT_.2")
                'pdf.SetCampo("E/OTT_.29", "E/OTT_.29")
                'pdf.SetCampo("E/OTT_.28", "E/OTT_.28")
                'pdf.SetCampo("E/AGO_.10", "E/AGO_.10")
                'pdf.SetCampo("E/AGO_.11", "E/AGO_.11")
                'pdf.SetCampo("E/AGO_.12", "E/AGO_.12")
                'pdf.SetCampo("E/AGO_.13", "E/AGO_.13")
                'pdf.SetCampo("E/DIC_.7", "E/DIC_.7")
                'pdf.SetCampo("E/AGO_.1", "E/AGO_.1")
                'pdf.SetCampo("E/MAG_.14", "E/MAG_.14")
                'pdf.SetCampo("E/MAG_.15", "E/MAG_.15")
                'pdf.SetCampo("E/MAG_.16", "E/MAG_.16")
                'pdf.SetCampo("E/MAG_.17", "E/MAG_.17")
                'pdf.SetCampo("E/MAG_.10", "E/MAG_.10")
                'pdf.SetCampo("E/MAG_.11", "E/MAG_.11")
                'pdf.SetCampo("nomefile", "nomefile")
                'pdf.SetCampo("E/MAG_.6", "E/MAG_.6")
                'pdf.SetCampo("E/GIU_.1", "E/GIU_.1")
                'pdf.SetCampo("Z2", "Z2")
                'pdf.SetCampo("E/MAG_.18", "E/MAG_.18")
                'pdf.SetCampo("D al 3  ", "D al 3")
                'pdf.SetCampo("D dal 1 ", "D dal 1")
                'pdf.SetCampo("E/GIU_.9", "E/GIU_.9")
                'pdf.SetCampo("H2", "H2")
                'pdf.SetCampo("I2", "I2")
                'pdf.SetCampo("E/MAR_.6", "E/MAR_.6")
                'pdf.SetCampo("L2", "L2")
                'pdf.SetCampo("M2", "M2")
                'pdf.SetCampo("N2", "N2")
                'pdf.SetCampo("A2", "A2")
                'pdf.SetCampo("E/LUG_.5", "E/LUG_.5")
                'pdf.SetCampo("C2", "C2")
                'pdf.SetCampo("D2", "D2")
                'pdf.SetCampo("E2", "E2")
                'pdf.SetCampo("cognome_echo", "cognome_echo")
                'pdf.SetCampo("G2", "G2")
                'pdf.SetCampo("indirizzoresidenza", "indirizzoresidenza")
                'pdf.SetCampo("H_data", "H_data")
                'pdf.SetCampo("E/DIC_.3", "E/DIC_.3")
                'pdf.SetCampo("nome", "nome")
                'pdf.SetCampo("E/FEBB_.23", "E/FEBB_.23")
                'pdf.SetCampo("E/AGO_.30 ", "E/AGO_.30")
                'pdf.SetCampo("azienda", "azienda")
                'pdf.SetCampo("C_datapreavv", "C_datapreavv")
                'pdf.SetCampo("specif altro", "specif altro")
                'pdf.SetCampo("E/APR_.8", "E/APR_.8")
                'pdf.SetCampo("E/GIU_.28", "E/GIU_.28")
                'pdf.SetCampo("E/GENN_.14", "E/GENN_.14")
                'pdf.SetCampo("E/GENN_.24", "E/GENN_.24")
                'pdf.SetCampo("telefono", "telefono")
                'pdf.SetCampo("E/FEBB_.12", "E/FEBB_.12")
                'pdf.SetCampo("E/MAG_.31", "E/MAG_.31")
                'pdf.SetCampo("comune nascita", "comune nascita")
                'pdf.SetCampo("qualifica 1", "qualifica 1")
                'pdf.SetCampo("C20", "C20")
                'pdf.SetCampo("inf  A", "inf  A")
                'pdf.SetCampo("E/OTT_.31", "E/OTT_.31")
                'pdf.SetCampo("E/OTT_.30", "E/OTT_.30")
                'pdf.SetCampo("E/NOV_.5", "E/NOV_.5")
                'pdf.SetCampo("E/DIC_.18", "E/DIC_.18")
                'pdf.SetCampo("E/DIC_.19", "E/DIC_.19")
                'pdf.SetCampo("qualifica altro", "qualifica altro")
                'pdf.SetCampo("E/DIC_.10", "E/DIC_.10")
                'pdf.SetCampo("D dal 4", "D dal 4")
                'pdf.SetCampo("E/DIC_.12", "E/DIC_.12")
                'pdf.SetCampo("E/DIC_.13", "E/DIC_.13")
                'pdf.SetCampo("E/DIC_.14", "E/DIC_.14")
                'pdf.SetCampo("E/MAG_.9", "E/MAG_.9")
                'pdf.SetCampo("E/DIC_.16", "E/DIC_.16")
                'pdf.SetCampo("E/DIC_.17", "E/DIC_.17")
                'pdf.SetCampo("E/FEBB_.18", "E/FEBB_.18")
                'pdf.SetCampo("E/FEBB_.28", "E/FEBB_.28")
                'pdf.SetCampo("telefax", "telefax")
                'pdf.SetCampo("E/MAG_.1", "E/MAG_.1")
                'pdf.SetCampo("E/FEBB_.14", "E/FEBB_.14")
                'pdf.SetCampo("E/AGO_.9", "E/AGO_.9")
                'pdf.SetCampo("E/AGO_.8", "E/AGO_.8")
                'pdf.SetCampo("E/SETT_.18", "E/SETT_.18")
                'pdf.SetCampo("E/FEBB_.17", "E/FEBB_.17")
                'pdf.SetCampo("E/SETT_.24", "E/SETT_.24")
                'pdf.SetCampo("E/SETT_.14", "E/SETT_.14")
                'pdf.SetCampo("codfisc_aziena", "codfisc_aziena")
                'pdf.SetCampo("E/MAG_.30", "E/MAG_.30")
                'pdf.SetCampo("E/GIU_.8", "E/GIU_.8")
                'pdf.SetCampo("E/AGO_.4", "E/AGO_.4")
                'pdf.SetCampo("datanascita", "datanascita")
                'pdf.SetCampo("D_al", "D_al")
                'pdf.SetCampo("codfisc", "codfisc")
                'pdf.SetCampo("E/MAR_.1", "E/MAR_.1")
                'pdf.SetCampo("E/GENN_.29", "E/GENN_.29")
                'pdf.SetCampo("E/LUG_.4", "E/LUG_.4")
                'pdf.SetCampo("E/OTT_.1", "E/OTT_.1")
                'pdf.SetCampo("E/AGO_.15", "E/AGO_.15")
                'pdf.SetCampo("E/AGO_.16", "E/AGO_.16")
                'pdf.SetCampo("E/AGO_.17", "E/AGO_.17")
                'pdf.SetCampo("Z1nascosto", "Z1nascosto")
                'pdf.SetCampo("E/MAG_.26", "E/MAG_.26")
                'pdf.SetCampo("D al 1", "D al 1")

                pdf.Compile()

                pdf.Dispose()



                'My.Computer.FileSystem.CopyFile(.NomeFileModello, Prestazione.FileOutPut)
            End If
        End With



    End Sub

    Private Function RetrieveSesso(ByVal Prest As Prestazione) As String


        If Prest.Utente.Sesso = AbstractPersona.Sex.Maschio Then
            Return "M"
        End If

        Return "F"


        'If Prest.Utente.Sesso.ToString().Equals("Maschio") = True Then
        'End If
    End Function

End Class