Imports WIN.TECHNICAL.PDF_PRINTER
Imports System.Runtime.InteropServices
Imports System.IO

Public Class PdfCompilerSetting4
    Implements IDocumentCreatorAdapter

    Private pdf As PdfCompiler
    Private tp As TipoPrestazione
    Private fileInput As String
    Private fileOutput As String
    <DllImport("kernel32.dll", SetLastError:=True)> _
    Public Shared Function LoadLibrary(ByVal lpFileName As String) As IntPtr
    End Function

    Public Sub CreateDocument(ByVal Prestazione As Prestazione) Implements IDocumentCreatorAdapter.CreateDocument
        Dim m_TipoPrestazione As TipoPrestazione = CType(Prestazione.TipoPrestazione, TipoPrestazione)

        With m_TipoPrestazione
            If .FileModelloExist Then

                Prestazione.SetFileOutput(.GetFileOutputName(Prestazione.Utente))

                tp = Prestazione.TipoPrestazione()
                fileInput = tp.NomeFileModello
                fileOutput = Prestazione.FileOutPut

                If (Environment.Version.Major >= 4) Then
                    Dim folder As String = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "..\Microsoft.NET\Framework\v2.0.50727")

                    folder = Path.GetFullPath(folder)

                    LoadLibrary(Path.Combine(folder, "vjsnativ.dll"))
                End If

                pdf = New PdfCompiler(fileInput, fileOutput)
                pdf.Setup()
                'pdf.SetCampo("nome", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("cognome coniuge", "")
                'pdf.SetCampo("datanascita", Prestazione.Utente.DataNascita)
                'pdf.SetCampo("M/F", RetrieveSesso(Prestazione))
                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)

                'pdf.SetCampo("comune nascita", Prestazione.Utente.ComuneNascita.Descrizione)

                'pdf.SetCampo("provnascita", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("cittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("comuneresidenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("indirizzoresidenza", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("provresidenza", Prestazione.Utente.Residenza.Provincia.Sigla)
                'pdf.SetCampo("capresidenza", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("telefono", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("email", Prestazione.Utente.Comunicazione.Mail)
                'pdf.SetCampo("sede inps", "")
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)
                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)


                '*******************************************************
                pdf.SetCampo("COGNOME", Prestazione.Utente.Cognome)
                pdf.SetCampo("NOME", Prestazione.Utente.Nome)
                pdf.SetCampo("DATA DI NASCITA", Prestazione.Utente.DataNascita)
                pdf.SetCampo("C.F.", Prestazione.Utente.CodiceFiscale)
                pdf.SetCampo("comune di nascita", Prestazione.Utente.ComuneNascita.Descrizione)
                pdf.SetCampo("PROV_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                pdf.SetCampo("comune di residenza", Prestazione.Utente.Residenza.Comune.Descrizione)
                pdf.SetCampo("PROV_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                pdf.SetCampo("CAP", Prestazione.Utente.Residenza.Comune.CAP)
                pdf.SetCampo("INDIRIZZO", Prestazione.Utente.Residenza.Via)
                pdf.SetCampo("tel fisso", Prestazione.Utente.Comunicazione.TelefonoCasa)
                pdf.SetCampo("tel cell", Prestazione.Utente.Comunicazione.Cellulare1)
                pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)




                'pdf.SetCampo("cognome coniuge", "")
                'pdf.SetCampo("M/F", RetrieveSesso(Prestazione))
                'pdf.SetCampo("domanda numero", "") 'Prestazione.Id.ToString())
                'pdf.SetCampo("nome_echo", Prestazione.Utente.Nome)
                'pdf.SetCampo("cognome_echo", Prestazione.Utente.Cognome)
                'pdf.SetCampo("codfisc_echo", Prestazione.Utente.CodiceFiscale)
                'pdf.SetCampo("cittadinanza", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("sede inps", "")
                'pdf.SetCampo("B_centro x l'imp_comune", "")
                'pdf.SetCampo("B_data1", "") 'Prestazione.DataRegistrazione)
                'pdf.SetCampo("B_data2", Prestazione.DataDocumento)
                'pdf.SetCampo("B_data3", Prestazione.DataDocumento)
                'pdf.SetCampo("M_sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("M_data", Prestazione.DataDocumento)
                'pdf.SetCampo("L_data", Prestazione.DataDocumento)
                'pdf.SetCampo("com_res", Prestazione.Utente.Residenza.Comune.Descrizione)
                'pdf.SetCampo("prov_nasc", Prestazione.Utente.ProvinciaNascita.Sigla)
                'pdf.SetCampo("comune_nasc", Prestazione.Utente.ComuneNascita.Descrizione)
                'pdf.SetCampo("stato_nasc", Prestazione.Utente.Nazionalita.Descrizione)
                'pdf.SetCampo("data_5", Prestazione.DataDocumento)
                'pdf.SetCampo("data_3", Prestazione.DataDocumento)
                'pdf.SetCampo("data_4", Prestazione.DataDocumento)
                'pdf.SetCampo("cap_res", Prestazione.Utente.Residenza.Comune.CAP)
                'pdf.SetCampo("prov_res", Prestazione.Utente.Residenza.Provincia.Sigla)
                ''pdf.SetCampo("stato_res", Prestazione.Utente.Residenza.Nazione.Descrizione)
                'pdf.SetCampo("ind_res", Prestazione.Utente.Residenza.Via)
                'pdf.SetCampo("data_2", Prestazione.DataDocumento)
                'pdf.SetCampo("num_tel", Prestazione.Utente.Comunicazione.TelefonoCasa)
                'pdf.SetCampo("num_cell", Prestazione.Utente.Comunicazione.Cellulare1)
                'pdf.SetCampo("sindacato", "FENEAL-UIL 03-03")
                'pdf.SetCampo("e-mail", Prestazione.Utente.Comunicazione.Mail)



                'pdf.SetCampo("tit_stu", "tit_stu")
                'pdf.SetCampo("DO_1.4", "DO_1.4")
                'pdf.SetCampo("E_al_3", "E_al_3")
                'pdf.SetCampo("inf  1.2", "inf  1.2")
                'pdf.SetCampo("TRA4", "TRA4")
                'pdf.SetCampo("DAZ4", "DAZ4")
                'pdf.SetCampo("CM_6", "CM_6")
                'pdf.SetCampo("DM_6", "DM_6")
                'pdf.SetCampo("DO_1.3", "DO_1.3")
                'pdf.SetCampo("B_giorni_2", "B_giorni_2")
                'pdf.SetCampo("ORA4", "ORA4")
                'pdf.SetCampo("INDIRIZZO", "INDIRIZZO")
                'pdf.SetCampo("n. figli 5", "n. figli 5")
                'pdf.SetCampo("DO_6.3", "DO_6.3")
                'pdf.SetCampo("CA_5", "CA_5")
                'pdf.SetCampo("E_ANNO_4", "E_ANNO_4")
                'pdf.SetCampo("n. percent 2", "n. percent 2")
                'pdf.SetCampo("DC_26", "DC_26")
                'pdf.SetCampo("DC_27", "DC_27")
                'pdf.SetCampo("DC_24", "DC_24")
                'pdf.SetCampo("DC_25", "DC_25")
                'pdf.SetCampo("DC_22", "DC_22")
                'pdf.SetCampo("DC_23", "DC_23")
                'pdf.SetCampo("DC_20", "DC_20")
                'pdf.SetCampo("DC_21", "DC_21")
                'pdf.SetCampo("DO_3.1", "DO_3.1")
                'pdf.SetCampo("inf  2.3", "inf  2.3")
                'pdf.SetCampo("DC_28", "DC_28")
                'pdf.SetCampo("CIG4", "CIG4")
                'pdf.SetCampo("DO_1.2", "DO_1.2")
                'pdf.SetCampo("ANF1", "ANF1")
                'pdf.SetCampo("TRA8", "TRA8")
                'pdf.SetCampo("DTOT5", "DTOT5")
                'pdf.SetCampo("st_civ", "st_civ")
                'pdf.SetCampo("DC_16", "DC_16")
                'pdf.SetCampo("PROV_res", "PROV_res")
                'pdf.SetCampo("TRA7", "TRA7")
                'pdf.SetCampo("DC_1", "DC_1")
                'pdf.SetCampo("COGNOME", "COGNOME")
                'pdf.SetCampo("F3", "F3")
                'pdf.SetCampo("DO_5.2", "DO_5.2")
                'pdf.SetCampo("inf  1.5", "inf  1.5")
                'pdf.SetCampo("TRA5", "TRA5")
                'pdf.SetCampo("DATA DI CESSAZIONE", "DATA DI CESSAZIONE")
                'pdf.SetCampo("B_giorni_1", "B_giorni_1")
                'pdf.SetCampo("TRA10", "TRA10")
                'pdf.SetCampo("DO_2.3", "DO_2.3")
                'pdf.SetCampo("COMP2", "COMP2")
                'pdf.SetCampo("DT_4", "DT_4")
                'pdf.SetCampo("CODBANPO", "CODBANPO")
                'pdf.SetCampo("DA3", "DA3")
                'pdf.SetCampo("CA_6", "CA_6")
                'pdf.SetCampo("CODCAB", "CODCAB")
                'pdf.SetCampo("MATRICOLA AZ", "MATRICOLA AZ")
                'pdf.SetCampo("E_ANNO_3", "E_ANNO_3")
                'pdf.SetCampo("n. percent 1", "n. percent 1")
                'pdf.SetCampo("ANF6", "ANF6")
                'pdf.SetCampo("DO_4.0.1", "DO_4.0.1")
                'pdf.SetCampo("inf  2.3b", "inf  2.3b")
                'pdf.SetCampo("E_al_2", "E_al_2")
                'pdf.SetCampo("inf  2.3a", "inf  2.3a")
                'pdf.SetCampo("CR_5", "CR_5")
                'pdf.SetCampo("TRA9", "TRA9")
                'pdf.SetCampo("DC_35", "DC_35")
                'pdf.SetCampo("E_dal_3", "E_dal_3")
                'pdf.SetCampo("DC_30", "DC_30")
                'pdf.SetCampo("n. figli 1", "n. figli 1")
                'pdf.SetCampo("DA1", "DA1")
                'pdf.SetCampo("DO_3.5", "DO_3.5")
                'pdf.SetCampo("DC_2", "DC_2")
                'pdf.SetCampo("n. figli 4", "n. figli 4")
                'pdf.SetCampo("PER1", "PER1")
                'pdf.SetCampo("DO_6.2", "DO_6.2")
                'pdf.SetCampo("TRA6", "TRA6")
                'pdf.SetCampo("DATA DI NASCITA", "DATA DI NASCITA")
                'pdf.SetCampo("DETR2", "DETR2")
                'pdf.SetCampo("E_dal_1", "E_dal_1")
                'pdf.SetCampo("CAP", "CAP")
                'pdf.SetCampo("DC_17", "DC_17")
                'pdf.SetCampo("descrizione", "descrizione")
                'pdf.SetCampo("ANF3", "ANF3")
                'pdf.SetCampo("DT_1", "DT_1")
                'pdf.SetCampo("DO_3.0", "DO_3.0")
                'pdf.SetCampo("NOME", "NOME")
                'pdf.SetCampo("E_ANNO_2", "E_ANNO_2")
                'pdf.SetCampo("e_mail", "e_mail")
                'pdf.SetCampo("E_MESE_2", "E_MESE_2")
                'pdf.SetCampo("tel cell", "tel cell")
                'pdf.SetCampo("CR_4", "CR_4")
                'pdf.SetCampo("DO_4.0.0", "DO_4.0.0")
                'pdf.SetCampo("DTOT6", "DTOT6")
                'pdf.SetCampo("DO_5.1", "DO_5.1")
                'pdf.SetCampo("CR_6", "CR_6")
                'pdf.SetCampo("inf  1.6", "inf  1.6")
                'pdf.SetCampo("DTOT3", "DTOT3")
                'pdf.SetCampo("DTOT1", "DTOT1")
                'pdf.SetCampo("B_ore_1", "B_ore_1")
                'pdf.SetCampo("DO_2.2", "DO_2.2")
                'pdf.SetCampo("CIG1", "CIG1")
                'pdf.SetCampo("inf  1.3", "inf  1.3")
                'pdf.SetCampo("DC_3", "DC_3")
                'pdf.SetCampo("CA_2", "CA_2")
                'pdf.SetCampo("PER2", "PER2")
                'pdf.SetCampo("CM_1", "CM_1")
                'pdf.SetCampo("DM_1", "DM_1")
                'pdf.SetCampo("comune di residenza", "comune di residenza")
                'pdf.SetCampo("OR1", "OR1")
                'pdf.SetCampo("DT_6", "DT_6")
                'pdf.SetCampo("DCAL4", "DCAL4")
                'pdf.SetCampo("DCAL5", "DCAL5")
                'pdf.SetCampo("DCAL2", "DCAL2")
                'pdf.SetCampo("DCAL3", "DCAL3")
                'pdf.SetCampo("DT_2", "DT_2")
                'pdf.SetCampo("n. percent 4", "n. percent 4")
                'pdf.SetCampo("E_al_1", "E_al_1")
                'pdf.SetCampo("tel fisso", "tel fisso")
                'pdf.SetCampo("E_dal_2", "E_dal_2")
                'pdf.SetCampo("E_ANNO_1", "E_ANNO_1")
                'pdf.SetCampo("F_dal", "F_dal")
                'pdf.SetCampo("DO_1.1", "DO_1.1")
                'pdf.SetCampo("E_MESE_1", "E_MESE_1")
                'pdf.SetCampo("DO_3.4", "DO_3.4")
                'pdf.SetCampo("DO_4.0.3", "DO_4.0.3")
                'pdf.SetCampo("n. figli 7", "n. figli 7")
                'pdf.SetCampo("DO_6.1", "DO_6.1")
                'pdf.SetCampo("CR_2", "CR_2")
                'pdf.SetCampo("CIG3", "CIG3")
                'pdf.SetCampo("di_fogli", "di_fogli")
                'pdf.SetCampo("CIG2", "CIG2")
                'pdf.SetCampo("DA5", "DA5")
                'pdf.SetCampo("DO_5.5", "DO_5.5")
                'pdf.SetCampo("DC_4", "DC_4")
                'pdf.SetCampo("PER3", "PER3")
                'pdf.SetCampo("CM_2", "CM_2")
                'pdf.SetCampo("DM_2", "DM_2")
                'pdf.SetCampo("n. figli 2", "n. figli 2")
                'pdf.SetCampo("DAZ5", "DAZ5")
                'pdf.SetCampo("ANF5", "ANF5")
                'pdf.SetCampo("CA_1", "CA_1")
                'pdf.SetCampo("DT_3", "DT_3")
                'pdf.SetCampo("comune di nascita", "comune di nascita")
                'pdf.SetCampo("DO_5.0", "DO_5.0")
                'pdf.SetCampo("DO_2.1", "DO_2.1")
                'pdf.SetCampo("DC_36", "DC_36")
                'pdf.SetCampo("DC_34", "DC_34")
                'pdf.SetCampo("DO_4.0.2", "DO_4.0.2")
                'pdf.SetCampo("DC_32", "DC_32")
                'pdf.SetCampo("DC_33", "DC_33")
                'pdf.SetCampo("TRA3", "TRA3")
                'pdf.SetCampo("DC_31", "DC_31")
                'pdf.SetCampo("DC_8", "DC_8")
                'pdf.SetCampo("dataversione", "dataversione")
                'pdf.SetCampo("DO_1.5", "DO_1.5")
                'pdf.SetCampo("DO_6.5", "DO_6.5")
                'pdf.SetCampo("ORA3", "ORA3")
                'pdf.SetCampo("DO_2.0", "DO_2.0")
                'pdf.SetCampo("protocollo", "protocollo")
                'pdf.SetCampo("inf  1.1", "inf  1.1")
                'pdf.SetCampo("TRA1", "TRA1")
                'pdf.SetCampo("DC_5", "DC_5")
                'pdf.SetCampo("inf  2.3c", "inf  2.3c")
                'pdf.SetCampo("PER4", "PER4")
                'pdf.SetCampo("CM_3", "CM_3")
                'pdf.SetCampo("DM_3", "DM_3")
                'pdf.SetCampo("inf  1.4", "inf  1.4")
                'pdf.SetCampo("DAZ6", "DAZ6")
                'pdf.SetCampo("CIN", "CIN")
                'pdf.SetCampo("DO_1.0", "DO_1.0")
                'pdf.SetCampo("nomefile", "nomefile")
                'pdf.SetCampo("DO_3.3", "DO_3.3")
                'pdf.SetCampo("qual", "qual")
                'pdf.SetCampo("F_al", "F_al")
                'pdf.SetCampo("n. figli 6", "n. figli 6")
                'pdf.SetCampo("B_dal_1", "B_dal_1")
                'pdf.SetCampo("DO_6.0", "DO_6.0")
                'pdf.SetCampo("B_dal_2", "B_dal_2")
                'pdf.SetCampo("DO_4.0.5", "DO_4.0.5")
                'pdf.SetCampo("cod_sind", "cod_sind")
                'pdf.SetCampo("CM_4", "CM_4")
                'pdf.SetCampo("CR_1", "CR_1")
                'pdf.SetCampo("ANF2", "ANF2")
                'pdf.SetCampo("DC_9", "DC_9")
                'pdf.SetCampo("DO_2.5", "DO_2.5")
                'pdf.SetCampo("DETR4", "DETR4")
                'pdf.SetCampo("DT_5", "DT_5")
                'pdf.SetCampo("TRA2", "TRA2")
                'pdf.SetCampo("DC_29", "DC_29")
                'pdf.SetCampo("DAZ2", "DAZ2")
                'pdf.SetCampo("E_dal_4", "E_dal_4")
                'pdf.SetCampo("DA6", "DA6")
                'pdf.SetCampo("DM_4", "DM_4")
                'pdf.SetCampo("DAZ1", "DAZ1")
                'pdf.SetCampo("ORA2", "ORA2")
                'pdf.SetCampo("DETR6", "DETR6")
                'pdf.SetCampo("n. figli 3", "n. figli 3")
                'pdf.SetCampo("n. figli 8", "n. figli 8")
                'pdf.SetCampo("DETR5", "DETR5")
                'pdf.SetCampo("E_al_4", "E_al_4")
                'pdf.SetCampo("DETR3", "DETR3")
                'pdf.SetCampo("DETR1", "DETR1")
                'pdf.SetCampo("CA_3", "CA_3")
                'pdf.SetCampo("DO_5.4", "DO_5.4")
                'pdf.SetCampo("DO_4.0.4", "DO_4.0.4")
                'pdf.SetCampo("DATA DI ASSUNZIONE", "DATA DI ASSUNZIONE")
                'pdf.SetCampo("DA4", "DA4")
                'pdf.SetCampo("E_MESE_3", "E_MESE_3")
                'pdf.SetCampo("C.F", "C.F")
                'pdf.SetCampo("DTOT4", "DTOT4")
                'pdf.SetCampo("DTOT2", "DTOT2")
                'pdf.SetCampo("CLIENT", "CLIENT")
                'pdf.SetCampo("DCAL6", "DCAL6")
                'pdf.SetCampo("DC_6", "DC_6")
                'pdf.SetCampo("DO_3.2", "DO_3.2")
                'pdf.SetCampo("DCAL1", "DCAL1")
                'pdf.SetCampo("DO_6.4", "DO_6.4")
                'pdf.SetCampo("E_MESE_4", "E_MESE_4")
                'pdf.SetCampo("DAZ3", "DAZ3")
                'pdf.SetCampo("n. percent 3", "n. percent 3")
                'pdf.SetCampo("CM_5", "CM_5")
                'pdf.SetCampo("DM_5", "DM_5")
                'pdf.SetCampo("PROV_nasc", "PROV_nasc")
                'pdf.SetCampo("DA2", "DA2")
                'pdf.SetCampo("n_foglio", "n_foglio")
                'pdf.SetCampo("F4", "F4")
                'pdf.SetCampo("DO_5.3", "DO_5.3")
                'pdf.SetCampo("CA_4", "CA_4")
                'pdf.SetCampo("COMP5", "COMP5")
                'pdf.SetCampo("COMP4", "COMP4")
                'pdf.SetCampo("DC_7", "DC_7")
                'pdf.SetCampo("COMP1", "COMP1")
                'pdf.SetCampo("COMP3", "COMP3")
                'pdf.SetCampo("DO_2.4", "DO_2.4")
                'pdf.SetCampo("DC_14", "DC_14")
                'pdf.SetCampo("DC_15", "DC_15")
                'pdf.SetCampo("DC_12", "DC_12")
                'pdf.SetCampo("DC_13", "DC_13")
                'pdf.SetCampo("DC_10", "DC_10")
                'pdf.SetCampo("DC_11", "DC_11")
                'pdf.SetCampo("ANF4", "ANF4")
                'pdf.SetCampo("CR_3", "CR_3")
                'pdf.SetCampo("DC_18", "DC_18")
                'pdf.SetCampo("DC_19", "DC_19")

                pdf.Compile()

                pdf.Dispose()



                'My.Computer.FileSystem.CopyFile(.NomeFileModello, Prestazione.FileOutPut)
            End If
        End With



    End Sub

    Private Function RetrieveSesso(ByVal Prest As Prestazione) As String


        If Prest.Utente.Sesso = AbstractPersona.Sex.Maschio Then
            Return "M"
        End If

        Return "F"


        'If Prest.Utente.Sesso.ToString().Equals("Maschio") = True Then
        'End If
    End Function

End Class