//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.17929
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIN.GUI.PRINT {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class ReportSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReportSettings defaultInstance = ((ReportSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReportSettings())));
        
        public static ReportSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Federazione Nazionale Lavoratori Edili Affini e del Legno")]
        public string ReportTitle {
            get {
                return ((string)(this["ReportTitle"]));
            }
            set {
                this["ReportTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sindacato Provinciale")]
        public string ReportSubTitle {
            get {
                return ((string)(this["ReportSubTitle"]));
            }
            set {
                this["ReportSubTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edili - Cementieri  - Manufatti Cemento  - Calce e Gesso  - Laterizi  - Legno - B" +
            "oschivi")]
        public string ReportSubTittle2 {
            get {
                return ((string)(this["ReportSubTittle2"]));
            }
            set {
                this["ReportSubTittle2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Via Annunziatella  n° 95")]
        public string ReportFooterTextVia {
            get {
                return ((string)(this["ReportFooterTextVia"]));
            }
            set {
                this["ReportFooterTextVia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matera")]
        public string ReportFooterTextCitta {
            get {
                return ((string)(this["ReportFooterTextCitta"]));
            }
            set {
                this["ReportFooterTextCitta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tel - fax: 0835 256450")]
        public string ReportFooterTextTelFax {
            get {
                return ((string)(this["ReportFooterTextTelFax"]));
            }
            set {
                this["ReportFooterTextTelFax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("feneal.matera@uilmt.it")]
        public string ReportFooterTextMail {
            get {
                return ((string)(this["ReportFooterTextMail"]));
            }
            set {
                this["ReportFooterTextMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.feneal-uil.it")]
        public string ReportFooterTextSitoWeb {
            get {
                return ((string)(this["ReportFooterTextSitoWeb"]));
            }
            set {
                this["ReportFooterTextSitoWeb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feneal - uil - Matera")]
        public string ReportTitlePersonalizzato {
            get {
                return ((string)(this["ReportTitlePersonalizzato"]));
            }
            set {
                this["ReportTitlePersonalizzato"] = value;
            }
        }
    }
}
